### ISSUE TITLE
what changes in mlvpn or ubond ?

### ISSUE THREAD

**Issue by rishabhsingh2** [markfoodyburton/ubond#3]

**Comment by markfoodyburton** [comment]
Complete re-write of the queuing mechanism (and re-order buffer, for better TCP support). Automatic bandwidth detection. Reduced failover time. Quite a lot.
However, many features will have suffered in the process. Not sure if encryption still works, the packaging mechanism probably no longer works, I didn't touch the BSD etc variants, so that are probably broken....

**Comment by rishabhsingh2** [comment]
if it is possible if not set mode= server or client both are act as a client or server means both are listen and generate connection to each other.
what make changes is possible?

**Comment by markfoodyburton** [comment]
sorry, I dont understand your English.

**Comment by rishabhsingh2** [comment]
> sorry, I dont understand your English.

in configuration file 

# Tunnel mode
# "server" will listen for connections
# "client" will just connect to "remotehost/remoteport"
mode = "client"

if mode is server. then this side mlvpn is just listen for connection if mode is client . then client side mlvpn just connect to remote side .
i want to both are act as a server or client.

**Comment by markfoodyburton** [comment]
Then you will have to build something that does that, set up a number of clients and a servers on each host, listening and connecting on different ports. You'll also need to set up routing to handle all of that. Good luck.

**Comment by rishabhsingh2** [comment]
Can you help us.

**Comment by markfoodyburton** [comment]
Yes. Are you willing to pay?

**Comment by rishabhsingh2** [comment]
How much?

**Comment by markfoodyburton** [comment]
send me your email address and I'll be in touch

**Comment by rishabhsingh2** [comment]
srishabh524@gmail.com

**Comment by rishabhsingh2** [comment]
please response????

**Comment by markfoodyburton** [comment]
I did, on your email...

**Comment by rishabhsingh2** [comment]
i didn't get any email. 
email- srishabh524@gmail.com

**Comment by markfoodyburton** [comment]
Maybe in a spam folder?

**Comment by rishabhsingh2** [comment]
ok
