### ISSUE TITLE
Compile error, `ubond_rtun_bind` function on OpenWrt & Bandwidth Algorithm Analysis

### ISSUE THREAD

**Issue by arinc9** [markfoodyburton/ubond#7]
Hiya. I've been using `MLVPN` on OpenWrt. I'm interested in checking your version, `ubond`.
`MLVPN` will crash with exitcode 1 (segfault?) on OpenWrt when trying to bind to an interface IP (bindhost). Which pretty much kills any use of multipath.

I made this makefile to compile `ubond` for OpenWrt. 
[Makefile.txt](https://github.com/markfoodyburton/ubond/files/6235078/Makefile.txt)

I also added the musl fix patch which is enough for `MLVPN` to be compiled.
It fails to compile ubond. Here's the compile log:
[compile+musl.log](https://github.com/markfoodyburton/ubond/files/6235072/compile%2Bmusl.log)

There's this error on the log:
```
ubond.c: In function 'ubond_rtun_bind':
ubond.c:1150:56: error: format not a string literal and no format arguments [-Werror=format-security]
       snprintf(ifr.ifr_name, sizeof(ifr.ifr_name) - 1, t->binddev);
                                                        ^
```

`MLVPN` will compile fine without this error but will exit with exitcode 1 when trying to bind to an interface IP.

Might there be something wrong with binding to interface IPs on `MLVPN` and `ubond` which makes this feature break on OpenWrt?

I believe a patch in the right place could solve this issue for compiling and make binding work on OpenWrt.

Got time to mess around about this?

**Comment by markfoodyburton** [comment]
I can't test on OpenWRT, and I dont know what compiler it uses, but google helps:
https://stackoverflow.com/questions/16011359/snprintf-format-not-a-string-literal-and-no-format-arguments-warning

If you put a patch together, I'd happily merge it

**Comment by arinc9** [comment]
Disclaimer: I don't know any coding languages, so I used common sense to change the source code.
Looking at the stackoverflow link you sent, I tried the 3rd answer (because it was the simplest thing to do). Changed `snprintf` to `strncpy`.

```c
--- a/src/ubond.c
+++ b/src/ubond.c
@@ -1147,7 +1147,8 @@ ubond_rtun_bind(ubond_tunnel_t *t)

     if (*t->binddev) {
       memset(&ifr, 0, sizeof(ifr));
-      snprintf(ifr.ifr_name, sizeof(ifr.ifr_name) - 1, t->binddev);
+      strncpy(ifr.ifr_name, sizeof(ifr.ifr_name) - 1, t->binddev);
+//      snprintf(ifr.ifr_name, sizeof(ifr.ifr_name) - 1, t->binddev);
       if (setsockopt(fd, SOL_SOCKET, SO_BINDTODEVICE, (void *)&ifr, sizeof(ifr)) < 0) {
         log_warn(NULL, "failed to bind on interface %s", t->binddev);
       }
```

It compiled fine, which I call it a success. I'm going to see if it actually works.
Let me know if you think that there's a better way to do this.

Update: `ubond` runs fine on OpenWrt. I did have bindhost on the config file but didn't see the log binding to any IP addresses.
I also never made ubond work so I'll have to test it on Linux server & client first.

**Comment by arinc9** [comment]
I've tried `ubond` on Linux with 4x 100mbps links. Here is what I found out about auto adjusting speeds.

Download speed would slowly go faster. It was highly unstable around 200mbps and would reach 310mbps max.
I tried the same links on MLVPN, I average ~350mbps and would reach 387mbps max.

It would let me reach higher upload speeds than MLVPN. I saw up to 40mbps. But it was very unstable and would average around 25mbps.
MLVPN would max ~27mbps, but if I were to specify the upload bandwidth properly for each link, it would average ~35mbps, max 40mbps.

Client and server logs are here.
[client.log](https://github.com/markfoodyburton/ubond/files/6253071/client.log)
[server.log](https://github.com/markfoodyburton/ubond/files/6253070/server.log)

I got what I needed so I'm closing the issue.

Thank you for your time.

**Comment by markfoodyburton** [comment]
Really useful findings - THANKS - it's probably to be expected. I would like to work on the algorithms at some point, because I think they are somewhat cautious. The fact it's finding a lot of packet loss, and that the links are taken down is - interesting. It really only does this as a last resort with high loss - which seems to imply that either your links are very dirty, or, we should accept a higher loss in order to get throughput..

If you have time - I'd be interested to know
a) what machine this was all running on, and how much cpu power it was taking - is ubond using too much resource from your open WRT device?
b) I use 'netdata' to monitor my links, - the graphs show how much data ubond thinks the link is capable of, how much data it's allowing on the links, how much noise/loss there is, etc etc... A screen-grab of a run would be really helpful...

**Comment by arinc9** [comment]
> either your links are very dirty, or, we should accept a higher loss in order to get throughput

It's probably the latter. All 4 links are broadband and are quite stable connections.
3 links are 100/11 mbps, one is 115/8 mbps link (I tested them thoroughly with a GNOME speed extension.) So the speeds are not identical.

a) I did the test on my Linux computer with an i7-8700k 6-core CPU. Pretty sure CPU is not causing bottleneck.
Though I'd like to run ubond again to see if it's multi-threaded.
I got Linksys WRT32X router with two cores. MLVPN on OpenWrt would run on one core only.
For unencrypted & no masqueraded connection, I get max 230mbps, ~224mbps stable on core1 at 100% load.
I haven't tried ubond on OpenWrt yet so I don't know if it would use all of the cores.

b) I'll do that on my Linux computer. It just takes time setting up VLANs & PPPoE tunnels & routing table & Ubond configuration and all haha.

**Comment by arinc9** [comment]
I have three issues to work on Ubond. So let's split them right now.

## Multi-thread
`ubond` won't run multithreaded. I'd get more performance on the router if it were to run multithreaded, could you do something about this? (Also opened an issue on MLVPN about this https://github.com/zehome/MLVPN/issues/151, author is not interested in doing so.)

## Bind to IP Issue on OpenWrt
- Ubond on OpenWrt won't bind to an IP address, therefore won't connect to the server. There aren't any updates after this:

```
root@OpenWrt:/etc/ubond# ubond -c ubond0.conf -u root --debug -vvv
2021-04-05T22:45:12 [WARN/reorder] Reset
2021-04-05T22:45:12 [ DBG] absolute maximum mtu: 1444
2021-04-05T22:45:12 [INFO/config] new password set
2021-04-05T22:45:12 [INFO/config] link1 tunnel added
2021-04-05T22:45:12 [WARN/config] Enabling automatic bandwidth adjustment
2021-04-05T22:45:12 [INFO] created interface `ubond0'
```

- I ran MLVPN on the same configuration (you heard that right, MLVPN client → Ubond server) and it would bind to an IP address fine. I'd even see the authenticated log on both sides.

```
root@OpenWrt:/etc/ubond# mlvpn -c ubond0.conf -u nobody --debug
2021-04-05T22:47:43 [INFO/config] new password set
2021-04-05T22:47:43 [INFO/config] link2 tunnel added
2021-04-05T22:47:43 [INFO] created interface `mlvpn0'
2021-04-05T22:47:43 [INFO] link2 bind to 100.84.95.106
2021-04-05T22:47:43 [INFO/protocol] link2 authenticated
```

```
2021-04-05T22:47:43 [INFO/protocol] link2 new connection -> redacted:31895
2021-04-05T22:47:43 [INFO] 1 tunnels up (normal mode)
2021-04-05T22:47:43 [INFO/protocol] link2 authenticated
2021-04-05T22:47:44 [INFO/rtt] link2 keepalive reached threashold, keepalive recieved 0.592486s ago
2021-04-05T22:47:44 [INFO] all tunnels are down or lossy but fallback is not available
2021-04-05T22:47:45 [INFO/rtt] link2 packet loss acceptable again: 0.000000%/31.000000%
2021-04-05T22:47:45 [INFO] 1 tunnels up (normal mode)
2021-04-05T22:47:46 [INFO/rtt] link2 keepalive reached threashold, keepalive recieved 0.599339s ago
2021-04-05T22:47:46 [INFO] all tunnels are down or lossy but fallback is not available
2021-04-05T22:47:46 [INFO/rtt] link2 packet loss acceptable again: 0.000000%/31.000000%
```

---

You can see that ubond won't bind to an IP address. I'm setting up `gdbserver` to debug what's going on. No idea if it's related to the patch that changes `snprintf` to `strncpy`. (Let me also mention the fact that I ran the patched version of `ubond` with this change on Linux, it would bind to an IP and authenticate just fine.)

## Packet Loss Algorithm Analysis
> A screen-grab of a run would be really helpful

I got to here, let me know what you specifically need.
![Screenshot from 2021-04-06 12-54-51](https://user-images.githubusercontent.com/29339981/113694599-a3320a00-96d8-11eb-89d4-930211a9e62f.png)

I'm open to chat with screen sharing if that makes testing stuff with `netdata` easier.
